### ISSUE TITLE
undefined is not an object (evaluating 'window.navigator.userAgent.indexOf')

### ISSUE THREAD

**Issue by rmemon** [formio/react-native-formio#19]
Import to Formio gives below error.

Error: undefined is not an object (evaluating 'window.navigator.userAgent.indexOf')

syntex: `import {Formio} from 'react-formio';`

![image](https://user-images.githubusercontent.com/13727755/44397286-7cd9f300-a55d-11e8-8ac0-27982ebb5d59.png)

Could please help me with the same.
Thank you in advance.

**Comment by randallknutson** [comment]
This repo is for the react-native implementation which is not yet ready for use unless you are willing to do some serious work to get it running. Your issue appears to be with the react-formio library which is a different library.
